package Lang_IVR.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;

public class IconContainer {
  protected static IconResource RESOURCE_a0a3a0a3b0i = new IconResource("KCL_Logo.jpg", IconContainer.class);
}
