package Lang_IVR.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAddNewCategory = createDescriptorForAddNewCategory();
  /*package*/ final ConceptDescriptor myConceptBack = createDescriptorForBack();
  /*package*/ final ConceptDescriptor myConceptCommand = createDescriptorForCommand();
  /*package*/ final ConceptDescriptor myConceptDialPadTemplate = createDescriptorForDialPadTemplate();
  /*package*/ final ConceptDescriptor myConceptDoAct = createDescriptorForDoAct();
  /*package*/ final ConceptDescriptor myConceptIncludeActivities = createDescriptorForIncludeActivities();
  /*package*/ final ConceptDescriptor myConceptMenuList = createDescriptorForMenuList();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAddNewCategory, myConceptBack, myConceptCommand, myConceptDialPadTemplate, myConceptDoAct, myConceptIncludeActivities, myConceptMenuList);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AddNewCategory:
        return myConceptAddNewCategory;
      case LanguageConceptSwitch.Back:
        return myConceptBack;
      case LanguageConceptSwitch.Command:
        return myConceptCommand;
      case LanguageConceptSwitch.DialPadTemplate:
        return myConceptDialPadTemplate;
      case LanguageConceptSwitch.DoAct:
        return myConceptDoAct;
      case LanguageConceptSwitch.IncludeActivities:
        return myConceptIncludeActivities;
      case LanguageConceptSwitch.MenuList:
        return myConceptMenuList;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAddNewCategory() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Lang_IVR", "AddNewCategory", 0x124f7f4fc7fa46ceL, 0x85780272621cca38L, 0x4c2e6accfaf690d6L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ce40d177-8989-49d2-b7f6-26310bc1d75b(Lang_IVR.structure)/5489442424427548886");
    b.version(2);
    b.property("InputKey", 0x4c2e6accfaf69a7aL).type(PrimitiveTypeId.STRING).origin("5489442424427551354").done();
    b.alias("Add new Category");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBack() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Lang_IVR", "Back", 0x124f7f4fc7fa46ceL, 0x85780272621cca38L, 0x4c2e6accfaf7f7b3L);
    b.class_(false, false, false);
    b.super_("Lang_IVR.structure.DoAct", 0x124f7f4fc7fa46ceL, 0x85780272621cca38L, 0x4c2e6accfaf7f94cL);
    b.origin("r:ce40d177-8989-49d2-b7f6-26310bc1d75b(Lang_IVR.structure)/5489442424427640755");
    b.version(2);
    b.alias("Back");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCommand() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Lang_IVR", "Command", 0x124f7f4fc7fa46ceL, 0x85780272621cca38L, 0x4c2e6accfaf7f815L);
    b.class_(false, true, false);
    b.origin("r:ce40d177-8989-49d2-b7f6-26310bc1d75b(Lang_IVR.structure)/5489442424427640853");
    b.version(2);
    b.alias("Command");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDialPadTemplate() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Lang_IVR", "DialPadTemplate", 0x124f7f4fc7fa46ceL, 0x85780272621cca38L, 0x4c2e6accfaf690d3L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:ce40d177-8989-49d2-b7f6-26310bc1d75b(Lang_IVR.structure)/5489442424427548883");
    b.version(2);
    b.property("Description", 0x51b0860915193ca0L).type(PrimitiveTypeId.STRING).origin("5886352086540041376").done();
    b.aggregate("IVRMenuUpdate", 0x4c2e6accfaf690e4L).target(0x124f7f4fc7fa46ceL, 0x85780272621cca38L, 0x4c2e6accfaf690deL).optional(false).ordered(true).multiple(false).origin("5489442424427548900").done();
    b.alias("KCL Dialpad Template");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDoAct() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Lang_IVR", "DoAct", 0x124f7f4fc7fa46ceL, 0x85780272621cca38L, 0x4c2e6accfaf7f94cL);
    b.class_(false, true, false);
    b.super_("Lang_IVR.structure.Command", 0x124f7f4fc7fa46ceL, 0x85780272621cca38L, 0x4c2e6accfaf7f815L);
    b.origin("r:ce40d177-8989-49d2-b7f6-26310bc1d75b(Lang_IVR.structure)/5489442424427641164");
    b.version(2);
    b.alias("DoAct");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIncludeActivities() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Lang_IVR", "IncludeActivities", 0x124f7f4fc7fa46ceL, 0x85780272621cca38L, 0x4c2e6accfaf690d9L);
    b.class_(false, false, false);
    b.origin("r:ce40d177-8989-49d2-b7f6-26310bc1d75b(Lang_IVR.structure)/5489442424427548889");
    b.version(2);
    b.property("playback", 0x55973a27cc9131e7L).type(PrimitiveTypeId.STRING).origin("6167462157317386727").done();
    b.associate("Dial_Label", 0x4c2e6accfaf690dcL).target(0x124f7f4fc7fa46ceL, 0x85780272621cca38L, 0x4c2e6accfaf690d6L).optional(false).origin("5489442424427548892").done();
    b.aggregate("Command", 0x4c2e6accfaf83215L).target(0x124f7f4fc7fa46ceL, 0x85780272621cca38L, 0x4c2e6accfaf7f815L).optional(false).ordered(true).multiple(false).origin("5489442424427655701").done();
    b.alias("Add new Activity");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMenuList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Lang_IVR", "MenuList", 0x124f7f4fc7fa46ceL, 0x85780272621cca38L, 0x4c2e6accfaf690deL);
    b.class_(false, false, false);
    b.super_("Lang_IVR.structure.Command", 0x124f7f4fc7fa46ceL, 0x85780272621cca38L, 0x4c2e6accfaf7f815L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x33d23ee961a0cbf3L);
    b.origin("r:ce40d177-8989-49d2-b7f6-26310bc1d75b(Lang_IVR.structure)/5489442424427548894");
    b.version(2);
    b.aggregate("Label", 0x4c2e6accfaf690dfL).target(0x124f7f4fc7fa46ceL, 0x85780272621cca38L, 0x4c2e6accfaf690d6L).optional(true).ordered(true).multiple(true).origin("5489442424427548895").done();
    b.aggregate("Activities", 0x4c2e6accfaf690e1L).target(0x124f7f4fc7fa46ceL, 0x85780272621cca38L, 0x4c2e6accfaf690d9L).optional(true).ordered(true).multiple(true).origin("5489442424427548897").done();
    b.alias("SubMenu");
    return b.create();
  }
}
