package Lang_IVR.editor;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;

public class IconContainer {
  protected static IconResource RESOURCE_a0a9c6h = new IconResource("arrow.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a01c6i = new IconResource("arrow.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a01c7i = new IconResource("menu.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c6h_0 = new IconResource("arrow.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a01c6i_0 = new IconResource("fix.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a01c7i_0 = new IconResource("fix.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a01c6j = new IconResource("remove.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a01c7j = new IconResource("plus.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c8j = new IconResource("add_to_list.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a01c9j = new IconResource("init.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c01j = new IconResource("remove.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c6h_1 = new IconResource("arrow.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c6h_2 = new IconResource("arrow.png", IconContainer.class);
}
